export const CARD_BUN = {
  _id: "643d69a5c3f7b9001cfa093d",
  name: "Флюоресцентная булка R2-D3",
  _uid: "1",
  quantity: 1,
  type: "bun",
  calories: 643,
  proteins: 44,
  fat: 26,
  carbohydrates: 85,
  price: 988,
  image: "https://code.s3.yandex.net/react/code/bun-01.png",
  image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
  image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
  __v: 0,
};

export const CARD_FILLING = {
  name: "Филе Люминесцентного тетраодонтимформа",
  calories: 643,
  proteins: 44,
  fat: 26,
  carbohydrates: 85,
  image_large: "https://code.s3.yandex.net/react/code/meat-03-large.png",
};

export const INGREDIENT_SAUCE = {
  _id: "643d69a5c3f7b9001cfa0943",
  _uid: "5",
  quantity: 1,
  name: "Соус фирменный Space Sauce",
  type: "sauce",
  calories: 14,
  proteins: 50,
  fat: 22,
  carbohydrates: 11,
  price: 80,
  image: "https://code.s3.yandex.net/react/code/sauce-04.png",
  image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
  image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
  __v: 0,
};

export const INGREDIENT_SAUCE_2 = {
  _id: "643d69a5c3f7b9001cfa0942",
  name: "Соус Spicy-X",
  _uid: "4",
  quantity: 1,
  type: "sauce",
  proteins: 30,
  fat: 20,
  carbohydrates: 40,
  calories: 30,
  price: 90,
  image: "https://code.s3.yandex.net/react/code/sauce-02.png",
  image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
  image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
  __v: 0,
};

export const INGREDIENT_MAIN = {
  _id: "643d69a5c3f7b9001cfa093e",
  name: "Филе Люминесцентного тетраодонтимформа",
  _uid: "4",
  quantity: 1,
  type: "main",
  calories: 643,
  proteins: 44,
  fat: 26,
  carbohydrates: 85,
  price: 988,
  image: "https://code.s3.yandex.net/react/code/meat-03.png",
  image_mobile: "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
  image_large: "https://code.s3.yandex.net/react/code/meat-03-large.png",
  __v: 0,
};

export const ORDER = {
  success: true,
  name: "Space люминесцентный флюоресцентный фалленианский бургер",
  order: {
    ingredients: [
      {
        _id: "643d69a5c3f7b9001cfa093d",
        name: "Флюоресцентная булка R2-D3",
        _uid: "1",
        quantity: 1,
        type: "bun",
        calories: 643,
        proteins: 44,
        fat: 26,
        carbohydrates: 85,
        price: 988,
        image: "https://code.s3.yandex.net/react/code/bun-01.png",
        image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
        __v: 0,
      },
      {
        _id: "643d69a5c3f7b9001cfa0943",
        name: "Соус фирменный Space Sauce",
        _uid: "2",
        quantity: 1,
        type: "sauce",
        calories: 14,
        proteins: 50,
        fat: 22,
        carbohydrates: 11,
        price: 80,
        image: "https://code.s3.yandex.net/react/code/sauce-04.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
        __v: 0,
      },
      {
        _id: "643d69a5c3f7b9001cfa0942",
        name: "Соус Spicy-X",
        _uid: "3",
        quantity: 1,
        type: "sauce",
        proteins: 30,
        fat: 20,
        carbohydrates: 40,
        calories: 30,
        price: 90,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        __v: 0,
      },      
      {
        _id: "643d69a5c3f7b9001cfa093e",
        name: "Филе Люминесцентного тетраодонтимформа",
        _uid: "4",
        quantity: 1,
        type: "main",
        calories: 643,
        proteins: 44,
        fat: 26,
        carbohydrates: 85,
        price: 988,
        image: "https://code.s3.yandex.net/react/code/meat-03.png",
        image_mobile: "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/meat-03-large.png",
        __v: 0,
      },
      {
        _id: "643d69a5c3f7b9001cfa0947",
        name: "Плоды Фалленианского дерева",
        _uid: "5",
        quantity: 1,
        type: "main",
        calories: 77,
        proteins: 20,
        fat: 5,
        carbohydrates: 874,
        price: 90,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        __v: 0,
      },
      {
        _id: "643d69a5c3f7b9001cfa093d",
        name: "Флюоресцентная булка R2-D3",
        _uid: "6",
        quantity: 1,
        type: "bun",
        calories: 643,
        proteins: 44,
        fat: 26,
        carbohydrates: 85,
        price: 988,
        image: "https://code.s3.yandex.net/react/code/bun-01.png",
        image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
        __v: 0,
      },
    ],
    _id: "6451f4b845c6f2001be7030f",
    owner: {
      name: "Тимс",
      email: "ben@mail.ru",
    //   createdAt: "2023-04-23T08:44:40.962Z",
    //   updatedAt: "2023-04-23T08:44:40.962Z",
    },
    status: "done",
    name: "Space люминесцентный флюоресцентный spicy бургер",
    createdAt: "2023-05-03T08:44:40.725Z",
    updatedAt: "2023-05-03T08:44:40.759Z",
    number: 2916,
    price: 2930,
  },
};

export const ORDER_SORTED = {
  success: true,
  name: "Space люминесцентный флюоресцентный фалленианский бургер",
  order: {
    ingredients: [
      {
        _id: "643d69a5c3f7b9001cfa093d",
        name: "Флюоресцентная булка R2-D3",
        _uid: "1",
        quantity: 1,
        type: "bun",
        calories: 643,
        proteins: 44,
        fat: 26,
        carbohydrates: 85,
        price: 988,
        image: "https://code.s3.yandex.net/react/code/bun-01.png",
        image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
        __v: 0,
      },
      {
        _id: "643d69a5c3f7b9001cfa0942",
        name: "Соус Spicy-X",
        _uid: "3",
        quantity: 1,
        type: "sauce",
        proteins: 30,
        fat: 20,
        carbohydrates: 40,
        calories: 30,
        price: 90,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        __v: 0,
      },
      {
        _id: "643d69a5c3f7b9001cfa0943",
        name: "Соус фирменный Space Sauce",
        _uid: "2",
        quantity: 1,
        type: "sauce",
        calories: 14,
        proteins: 50,
        fat: 22,
        carbohydrates: 11,
        price: 80,
        image: "https://code.s3.yandex.net/react/code/sauce-04.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
        __v: 0,
      },         
      {
        _id: "643d69a5c3f7b9001cfa093e",
        name: "Филе Люминесцентного тетраодонтимформа",
        _uid: "4",
        quantity: 1,
        type: "main",
        calories: 643,
        proteins: 44,
        fat: 26,
        carbohydrates: 85,
        price: 988,
        image: "https://code.s3.yandex.net/react/code/meat-03.png",
        image_mobile: "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/meat-03-large.png",
        __v: 0,
      },
      {
        _id: "643d69a5c3f7b9001cfa0947",
        name: "Плоды Фалленианского дерева",
        _uid: "5",
        quantity: 1,
        type: "main",
        calories: 77,
        proteins: 20,
        fat: 5,
        carbohydrates: 874,
        price: 90,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        __v: 0,
      },
      {
        _id: "643d69a5c3f7b9001cfa093d",
        name: "Флюоресцентная булка R2-D3",
        _uid: "6",
        quantity: 1,
        type: "bun",
        calories: 643,
        proteins: 44,
        fat: 26,
        carbohydrates: 85,
        price: 988,
        image: "https://code.s3.yandex.net/react/code/bun-01.png",
        image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
        image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
        __v: 0,
      },
    ],
    _id: "6451f4b845c6f2001be7030f",
    owner: {
      name: "Тимс",
      email: "ben@mail.ru",
    //   createdAt: "2023-04-23T08:44:40.962Z",
    //   updatedAt: "2023-04-23T08:44:40.962Z",
    },
    status: "done",
    name: "Space люминесцентный флюоресцентный spicy бургер",
    createdAt: "2023-05-03T08:44:40.725Z",
    updatedAt: "2023-05-03T08:44:40.759Z",
    number: 2916,
    price: 2930,
  },
};

export const USER = {
  name: "Тимс",
  email: "ben@mail.ru",
  password: "12345678",
  code: "test",
};

export const WS_ORDER = {
  ingredients: [
    "643d69a5c3f7b9001cfa093d",
    "643d69a5c3f7b9001cfa0943",
    "643d69a5c3f7b9001cfa0942",
    "643d69a5c3f7b9001cfa093e",
    "643d69a5c3f7b9001cfa0947",
    "643d69a5c3f7b9001cfa093d",
  ],
  _id: "6451f4b845c6f2001be7030f",
  status: "done",
  name: "Space люминесцентный флюоресцентный фалленианский бургер",
  number: 2916,
  createdAt: "2023-05-03T08:44:40.725Z",
  updatedAt: "2023-05-03T08:44:40.759Z",
};

export const WSORDERDATA_SIMPLE = {
  orders: [WS_ORDER],
  total: 1,
  totalToday: 1,
};

export const WSORDERDATA = {
  success: true,
  orders: [WS_ORDER],
  total: 1,
  totalToday: 1,
};

